### ISSUE TITLE
Selection Highlight Color Issue in Terminal

### ISSUE THREAD

**Issue by RomFatal** [boterop/amoled_saver_pro#15]
The selection highlight color in my terminal is black, which matches the background color, making it difficult to discern selected text. This issue persists when using commands in the terminal. As a result, it's challenging to identify which text is selected, hindering productivity and causing potential errors. We need to address this color contrast issue to improve user experience and usability when working with the terminal. The rest is Great Thank You.

![image](https://github.com/boterop/amoled_saver_pro/assets/39658012/5bf387b8-87a8-4672-a6b4-48a867932733)

**Comment by boterop** [comment]
Hi. thanks for the issue. this is solved and available to update in your vs code :metal: 
![image](https://github.com/boterop/amoled_saver_pro/assets/98826652/6fa852d5-9bad-4c83-9fea-100298b9193f)

**Comment by RomFatal** [comment]
Thanks for the quick fix! Really appreciate it. 🙏
